# Generated by Django 4.0.10 on 2024-04-28 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('born', models.CharField(max_length=250)),
                ('nationality', models.CharField(max_length=100)),
                ('height', models.CharField(max_length=200)),
                ('weight', models.CharField(max_length=200)),
                ('nba_draft', models.CharField(max_length=250)),
            ],
        ),
    ]
